export { H1 } from './H1'
export type { H1Props } from './H1'
export { H2 } from './H2'
export type { H2Props } from './H2'
export { BodyLarge } from './BodyLarge'
export type { BodyLargeProps } from './BodyLarge'
export { Body } from './Body'
export type { BodyProps } from './Body'
export { ButtonText } from './ButtonText'
export type { ButtonTextProps } from './ButtonText'
export { Small } from './Small'
export type { SmallProps } from './Small'
export { Micro } from './Micro'
export type { MicroProps } from './Micro'
